### ISSUE TITLE
Publish on the Powershell Gallery?

### ISSUE THREAD

**Issue by ctolkien** [latkin/1poshword#10]
http://www.powershellgallery.com/

**Comment by latkin** [comment]
Good call, will do this.

Did most of the deving on Mac, where gallery doesn't work (ref https://github.com/PowerShell/PowerShell/issues/1773). Published workaround also didn't work 😢 . So didn't take the time to do this earlier.

**Comment by latkin** [comment]
Done - https://www.powershellgallery.com/packages/1Poshword
