### ISSUE TITLE
Add items (logons) to vault

### ISSUE THREAD

**Issue by jaredcatkinson** [latkin/1poshword#11]
Thanks for this project! I love the idea of being able to easily create a PSCredential from a logon. Have you looked into the difficulty of adding items, particularly logons, to a vault?

**Comment by latkin** [comment]
Hi @jaredcatkinson. I know I'm a year and a half late, but thanks for taking the time to log an issue.

Reading items is significantly easier, and carries much less security risk, than adding items. It is definitely possible for a client like this to add entries, but for my own purposes I don't plan to add that to the scope of this project right now.

For now I can mostly ignore all of the various additional meta fields that are stored in the vault, and focus on the most recent username/password. If we were adding write support, a lot of additional stuff would need to be considered to ensure everything is "just so" and the entry will be compatible with the desktop clients.

A write client also carries the burden of performing the password generation and encryption steps correctly and securely, or else the entry will be stored in a way that could be compromised. I'd prefer to avoid worrying about that in this project.
